name: CI Next.js

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Instalar e Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Instalar dependências
        run: npm install

      - name: Lint (opcional)
        run: npm run lint

      - name: Testes (opcional)
        run: npm test

      - name: Build da aplicação
        run: npm run build

      - name: Verificar build
        run: ls -R .next
