name: CI Next.js

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Install and Build Next.js
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_BASE_URL: https://api.agrofast.tech
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Node.js Setup
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        id: cache-npm-deps
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install NPM dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build
